### PR TITLE
[DO NOT MERGE] - Changes to calendar.on() results

### PR DESCRIPTION
**Pull request by dontgoplastic**
Hello,

Thanks for making this nice utility! I needed to make some modifications for a project I'm working on and I thought you might want to consider incorporating them into your main repo.

I figure it would make the most sense for you to [review my fork](https://github.com/dontgoplastic/calendar-js) to see if you liked the general direction before continuing, hence the "DO NOT MERGE" in the title. If you liked it, then I can make edits to the readme to be more in tune with your API documentation (as opposed to the explanation of what's different between my fork and your base). I can also write tests for the changes.

If you're not interested then no problem. I realize this is a fairly big change from what's currently setup.

Thanks again and let me know!

### CODE REVIEW

**Comment by dontgoplastic** [comment]
I just noticed the discussion on issue #4 - The requested additional properties would be fairly trivial to include in the month dataset with my changes. So that's pretty sweet 👌

**Comment by igor-ribeiro** [comment]
I get it. I think the `calendarDetailed` can fit this need, we can put all the information there without changing the API. I like the idea of passing a callback to `.of` to transform the data any way you want. Thanks!

**Comment by dontgoplastic** [comment]
Great - I can get started on the following:

* Revert/remove all `useLegacyApi` config stuff
* Set the new the new "week arrays of date descriptor objects" to a new `calendarDetailed` property, living alongside the existing `calendar` array
* Get the readme into a better spot for merging

I should be able to wrap that up in the next few days or so.

If you have any suggestions on what the additional tests should be, please let me know. TDD is not my forte, so any input would be appreciated.

**Comment by igor-ribeiro** [comment]
@dontgoplastic Awesome, I think `calendarDetailed` is better than changing the whole API now. I recommend you to create a new PR, so thing are clearer. About the testing, just make sure that the data is there in the right format, you can follow the current tests. I'm closing this.

**Pull request closed without merging**
